### ISSUE TITLE
decodeURI is creating null bytes

### ISSUE THREAD

**Issue by beders** [JuliaWeb/HttpCommon.jl#10] opened 2014-08-24 03:43 UTC
Here's a simple test case (using Morsel):
```julia
using Morsel
using HttpServer.parsequerystring
app = Morsel.app()

post(app, "/proc") do req, res
    println(parsequerystring(req.http_req.data))
    "Result $(parsequerystring(req.http_req.data)) !"
end
start(app, 8000)
```

Then run:
```bash
curl -POST 'http://localhost:8000/proc' -d "name=Jim"
```

Result on my machine (Mac OS X Mavericks, Julia 0.3.0) is:
Result ["name"=>"Jim\b\0\0\0\0\0\0\0"] !

**Comment by sbromberger** [comment] 2015-02-12 17:32
Can't reproduce in 0.4.0 or in 0.3.5 on OSX Yosemite:

```
julia> start(app, 8000)
Morsel is listening on 8000...
Dict{AbstractString,AbstractString}("name"=>"Jim")
```

**Comment by malmaud** [comment] 2015-08-14 03:16
Closing as not reproducible. Feel free to reopen if this is still a problem.

**Closed by malmaud** 2015-08-14 03:16 UTC
